<?php
/* 
Template Name: Terms
*/
get_header();
//print_r($_REQUEST);

?>


<section class="hero_banner" style="background-image: linear-gradient(to right, rgb(16 129 147 / 75%), rgb(23 132 124 / 75%), rgb(66 132 95 / 75%), rgb(103 128 68 / 76%), rgb(138 120 54 / 75%)), url(<?php echo home_url(); ?>/wp-content/uploads/2021/03/hero-img.jpg); height: 30vh;">
      
    </section>
<div class="mainContainer">
	<section class="section_box ">   		
        <div class="container ">
        	<div class="row mb-80">
        		<div class="col-md-12 mt-50">
        			<?php 
foreach( WC()->cart->get_cart() as $cart_item ) {
						$product = $cart_item['data'];
					//	print_r($product);
			        if( $product->is_type( 'variation' ) ){ ?>

        			<h1>The Black Powder XChange Terms &amp; Condition</h1>
<p>These terms and conditions (the “Agreement” or “Terms”) govern participation in any Flight Club VIP owned and operated event, as well as various products and offerings (the “Offerings”) that may be offered as part of the Event.</p>
<p>By registering for The Black Powder XChange and/or participating in any Offerings you agree to these Terms, which form a legally binding contract between Flight Club VIP, LLC, a Texas limited liability company (“FCV” “Company” or “Event Host”) and the registered participant (“you” or “Participant”). If you are registering on behalf of another individual, it is your responsibility to ensure the person participating is aware of these Terms and accepts them. By completing the registration on behalf of another individual you are warranting that you have made the Participant aware of these terms and that they have accepted these terms.</p>
<p>You acknowledge and agree that it is your responsibility to review these Terms before registering for The Black Powder XChange or participating in any Offerings. Your decision to register for the Event and/or participate in any Offerings after such modifications are made will constitute acknowledgment and acceptance of the Terms.</p>
<p>The following Terms and Conditions relate to your booking with Flight Club VIP, and yourself (“Event Attendee”) and where applicable shall incorporate the following Booking Terms and Conditions.</p>
<p>&nbsp;</p>
<p><strong>1. Passport</strong><br>
A valid passport is required for U.S. Citizens traveling internationally. Visit&nbsp;<a href="http://www.travel.state.gov/" target="_blank" rel="noopener"><span style="color: #1155cc;"><u>www.travel.state.gov</u></span></a>&nbsp;for specific requirements. If you are not a U.S. Citizen, please check with the consulate of the country to which you are traveling for entry requirements.</p>
<p>&nbsp;</p>
<p><strong>2. Refund Policy and Payments</strong></p>
<ul>
<li><b>Refund Policy.</b>&nbsp;Please be advised that this is a non-refundable event. We recommend that travelers purchase travel insurance to protect.</li>
<li><b>Payment.</b>&nbsp;All registrants must abide by the payment schedule set forth below. A late fee of $50 will be applied for all balances that go unpaid by the specified dates below. The cost will increase $25 every 5 days that a registrant’s balance goes unpaid.</li>
</ul>
<p><b>Payment Due Dates</b></p>
<p>May 1st – 25% of Registration Fee</p>
<p>July 1st – 50% of Registration Fee</p>
<p>September 1st – 75% of Registration Fee</p>
<p>October 23rd (45 days before travel) – Final Payment Due</p>
<p>&nbsp;</p>
<p><strong>3. Disruptive Conduct.</strong></p>
<p>You acknowledge and agree that FCV reserves the right, in its sole discretion, to remove you from the Event if it determines that your participation or behavior creates a disruption or hinders the Event or the enjoyment of the Event by other attendees.</p>
<p>&nbsp;</p>
<p><strong>4.&nbsp;Media Release</strong></p>
<p>By participating in the Event, you acknowledge and agree to grant FCV the right at the Event to record, film, live stream, photograph, or capture your likeness in any media now available or hereafter developed and to distribute, broadcast, use, or otherwise to disseminate globally, in perpetuity, such media without any further approval from you or any payment to you. This grant to FCV includes, but is not limited to, the right to edit such media, the right to use the media alone or together with other information, and the right to allow others to use or disseminate the media.</p>
<p>&nbsp;</p>
<p><strong>5.&nbsp;Limitation of Liability, COVID-19 Waiver</strong></p>
<p><b>Limitation of Liability.</b>&nbsp;Except as required by law, neither Flight Club VIP, nor its affiliates shall be liable for any direct, indirect, special, incidental, or consequential costs, damages or losses arising directly or indirectly from the Event or other aspect related thereto or in connection with this Agreement. The maximum aggregate liability of FCV for any claim in any way connected with, or arising from, the Event or this Agreement, whether in contract, tort, or otherwise (including any negligent act or omission), shall be limited to the amount paid by you to FCV under this Agreement.</p>
<p>FCV, and their employees, affiliates, officers, directors, successors, agents, and assigns do not own or operate any entity which provides goods and services for your travel including without limitation, lodging facilities, airline, vessel, motor coach or other transportation companies, guides or guide services, local ground operators, providers or organizers of optional excursions, food service providers, etc. All such persons and entities are independent contractors and are in no way affiliated with FCV. FCV is not liable for any negligent or willful act or failure to act of any travel service provider or of any third party. FCV is not responsible for any injury, loss, death, inconvenience, delay or damage to person or property in connection with the provision of any goods or services whether resulting from, but not limited to, acts of God or force majeure, illness, disease, acts of war or civil unrest, insurrection or revolt, animals, strike or other labor activities, criminal or terrorist activities, of any kind, overbooking or downgrading of accommodations, mechanical or other failure of airplanes or other means of transportation, or any failure of any transportation mechanism to arrive or depart on time. If due to weather, flight schedules or other uncontrollable factors you are required to spend additional night(s), you will be responsible for your own hotel, transfers, and meal costs. Baggage is entirely at owner’s risk. You specifically agree that FCV is not liable for any consequential loss or damage.</p>
<p><b>Coronavirus Waiver.&nbsp;</b>The novel coronavirus, COVID-19, has been declared a worldwide pandemic by the World Health Organization. COVID-19 is reported to be extremely contagious. The virus spreads through person-to-person contact and/or by contact with contaminated surfaces and objects, and even possibly in the air in the form of droplets. Participants can be infected and show no symptoms and therefore spread the disease. There are known vaccines that many of the U.S. population has received to prevent spreading and contracting of the disease. In addition, mask usage and washing of hands are highly encouraged to prevent spread and contracting.&nbsp; Evidence has shown that COVID-19 can cause serious and potentially life-threatening illness and even death. FCV, its respective representatives, affiliates, licensees, successors and assigns (collectively and individually a “Released Party”) cannot prevent you or members of your household from becoming exposed to, contracting, or spreading COVID-19 while attending FCV Events. It is not possible to prevent the presence of the disease. Therefore, if you choose to attend FCV Events, you may be exposing yourself to and/or increasing your risk of contracting or spreading COVID-19. Acknowledging such, you release FCV of any liability if you contract COVID-19. You hereby choose to accept the risk of contracting COVID-19 for yourself and/or members of your household in order to attend FCV Events.</p>
<p><b>Dispute Resolution.</b>&nbsp;Any dispute, controversy or claim arising out of or related in any way to this Amendment, or any services performed hereunder which cannot be amicably resolved by the parties shall be solely and finally settled by arbitration administered by the (American Bar Association) in accordance with its commercial arbitration rules. Judgment on the award rendered by the arbitrator(s) may be entered in any court having jurisdiction thereof. The arbitration shall take place before a panel of three (3) arbitrators sitting in Texas. The language of the arbitration shall be English. The arbitrators will be bound to adjudicate all disputes in accordance with the laws of the State of Texas. The decision of the arbitrators shall be in writing with written findings of fact and shall be final and binding on the parties. Each party shall bear its own costs relating to the arbitration proceedings irrespective of its outcome. This section provides the sole recourse for the settlement of any disputes arising out of, in connection with, or related to this Amendment.</p>
<p><b>Entire Agreement.&nbsp;</b>This Agreement constitutes the entire agreement between the Parties and supersedes any prior understanding or representation of any kind preceding the date of this Agreement. There are no other promises, conditions, understandings, or other agreements, whether oral or written, relating to the subject matter of this Agreement.</p>
<p><b>By agreeing to these terms, I agree I am 21+ years of age.</b></p>
	
        			
			        	<?php 			        	
			        }else{ ?>
        			<h1>Terms &amp; Conditions</h1>
<p>These Terms and Conditions apply to the use by any party of the website and related online information and transaction platform (the “Website”) provided by Flight Club VIP.<br>
In addition to these Terms and Conditions the Privacy Policy of Flight Club VIP is applicable.</p>
<p>We may revise these Terms at any time without notice by posting Revised Terms on the Website. Such Revised Terms shall be effective as to all use of the Website from and after their posting, and your sole remedy should you disagree with any Revised Terms shall be to cease use of the Website.</p>
<p>These Terms &amp; Conditions were last updated on January 1, 2019.</p>
<p><strong>Approval of Terms and Conditions</strong></p>
<p>By viewing, using, or otherwise interacting with the Website, you agree to be bound by these Terms. If you do not agree to any of these Terms, please do not use the Website or any other service offered electronically by Flight Club VIP.</p>
<p><strong>Access and Use</strong></p>
<p>By using this Site, you represent and warrant that (a) all registration information you submit is truthful and accurate; (b) you will maintain the accuracy of such information; (c) you are thirteen (13) years of age or older; and (d) your use of the Site does not violate any applicable law. We reserve the right to terminate the accounts and remove the profiles of any users that we believe have breached these Terms and Conditions.</p>
<p><strong>Information and Services For VIP Packages and Events</strong></p>
<p>The Website provides, among other things, information pertaining to events or travel packages (”VIP Packages”) and/or single travel services (“Single Services”) offered by third parties (“Tour Providers”), and in many cases, allows a Client to request a booking from, and process payments to, Tour Providers, through the Website.</p>
<p>VIP Packages” means a pre-arranged combination of at least two of the following: (a) transport (b) accommodation or (c) another tourist service forming a significant part of the Client’s booking, where those two or more components are sold to the Client as a whole at the same time on our online platform at an all-inclusive price.</p>
<p><strong>Use of Information Free of Charge; Termination of Service</strong></p>
<p>Use of the Website is presently free of charge for accessing, reading and browsing Flight Club VIP’s travel information and/or to request and confirm a booking of VIP Packages with a Tour Provider. We reserve the right to modify our charges or policies regarding use of the Website at any time by posting such modifications on the Website.</p>
<p>Flight club VIP may at times be compensated by commissions or other amounts from Tour Providers (or related parties) relative to the offering of these services as well as the processing of booking requests and payments. Review, usage, and interaction on the website is acknowledgement that you have been informed of such relationships.</p>
<p>Flight club VIP reserves the right to terminate any person’s access to the Website at any time, for any reason, and without notice.</p>
<p><strong>Information on Website; No Representations</strong></p>
<p>“Information pertaining to Events, VIP Packages, and Single Services is provided by Tour Providers and other third parties. Tour Providers are individually responsible for updating all pricing, rates, charges, applicable taxes, rules, and regulations, and all other Tour Information, pertaining to their particular service offerings displayed on the Website. As such, you acknowledge that Flight club VIP has no responsibility for the accuracy or other characteristics of any Tour Information, and you agree that solely the applicable Tour Providers are responsible therefor.</p>
<p>Although we use reasonable care in updating and maintaining the Website, we cannot guarantee that all information is accurate, updated, complete or correct, nor can we be held responsible for any errors, interruptions, inaccurate, misleading or untrue information or non-delivery of information.</p>
<p>The Website may contain links to websites controlled by parties other than Flight club VIP (“”Third-Party Websites””). Flight Club VIP is not responsible for the availability of, contents on, charges incurred on, or your other use of, Third-Party Websites. Flight Club VIP provides links to Third-Party Websites solely as a convenience to Clients, and the inclusion of any link does not imply endorsement by Flight club VIP of a Third-Party Website. You bear all risks associated with Third-Party Websites, and Flight Club VIP is not responsible for any claim, loss, or damage relating to or arising out of any Third-Party Website or your use thereof.</p>
<p>Flight Club VIP hereby disclaims all warranties, including without limitation the warranties of merchantability or fitness for a particular purpose, relating to the Website, any Tour Packages, Single Services, or any Tour Information or other information available on or through the Website. We do not warrant that the Website operation will be uninterrupted, error free or that any information or other material accessible from the Website is free of viruses and/or other harmful components. The Website is provided on an “”as is”” and an “”as available”” basis. Each Client assumes all responsibility and takes the sole risk for the use of the Website and using the services offered from the Website.</p>
<p>Flight Club VIP is not responsible for any errors, omissions, late or missing updates, misleading information provided by Tour Providers or other third parties, and we disclaim, to the maximum extent permitted by law, all express and implied warranties and all other responsibilities in connection with such information.</p>
<p>All photographs used are for the purposes of illustration only and should not be taken to be literal representations of actual facilities, accommodations or services offered unless otherwise advised.</p>
<p><strong>Links to third party web sites</strong></p>
<p>The Site may include links to third party websites that are controlled and maintained by others. These links should not be interpreted as an endorsement by Flight Club VIP of the sites linked or referred to, nor does Flight Club VIP have any control over the content of any such sites. Flight Club VIP will not be liable for any loss or damage that may arise from your use of such websites.</p>
<p><strong>Disclaimer</strong></p>
<p>Every effort has been made to ensure that the information on the Site is as up-to-date as possible. Some details, however, such as telephone numbers, travel information and website addresses are liable to change. Flight Club VIP does not accept any responsibility for any consequences arising from the use of this information, nor for any material on third party websites and cannot guarantee that any third party websites listed will be a suitable source of travel information.</p>
<p>In addition, we have made every effort to ensure that any content sent to and displayed on the website from users, members and other third parties is appropriate to this website; however, we cannot guarantee 100% accuracy, or that it is a suitable source of travel information. However, we value your comments, views and suggestions very highly so feel free to contact us at info@flightclub.vip</p>
<p>The Site is provided by Flight Club VIP in good faith but Flight Club VIP does not make any representations or warranties of any kind, express or implied, in relation to all or any part of the Site or the Content or any websites to which the Site is linked, and all warranties and representations are hereby excluded to the extent permitted by law.</p>
<p>There is no guarantee that the Site will be free of infection by viruses or anything else which may be harmful or destructive. To the extent permitted by law, Flight Club VIP hereby disclaims all liability in connection with any loss and/or damage, arising out of or in connection with any use of, or inability to use, all or any part of the Content, the Site and/or any website to which the Site is linked, or any action taken (or refrained from being taken) as a result of using any of these.</p>
<p><strong>Ratings and Client Reviews</strong></p>
<p>The ratings of VIP Packages, their components, and Single Services are based on the reviews of Clients, and should be regarded as survey results, obtained without any further commercial offer or incentive in order to maintain the objectivity of such ratings to the maximum extent possible. We offer these ratings, as-is, without any representation, warranty, or other obligation on our part, as a service to Clients. We reserve the right to refuse or remove information and/or reviews at our sole discretion, but we have no obligation to do so.</p>
<p>The information presented on the Website does not constitute and may not be regarded as a recommendation or endorsement of the quality, service level, qualification or (star) rating of any Tour Provider or any VIP Packages and/or other tourist services.</p>
<p><strong>Client/ Website User Obligations</strong></p>
<p>Each Client who purchases a VIP Package or Single Service is personally responsible to follow the requirements outlined by the Tour Provider and/or the local authorities for such service. These requirements may include, without limitation, passport and/or visa requirements, compliance with customs, requirements pertaining to personal health, and rules and processes established by Tour Providers relative to participation in given tour services.</p>
<p>Each Client is also responsible for timely arrival at the embarkation/departure point and each meeting point during the VIP Packages indicated by the Tour Provider.</p>
<p>To utilize certain features of the Website, we may require you to register a user account or otherwise provide a valid email address or other contact information. You warrant and represent that the information you submit to us is true and accurate. Your failure to submit true and accurate information may result in termination of your account or loss of your bookings, and Flight Club VIP reserves all remedies with respect to any false information submitted to us and/or the Website.</p>
<p>Please be sure to keep your user and account information, including but not limited to your log-in information, secret, as unauthorized access to your account may result in charges for transactions that you did not intend to incur and for which you will be held responsible. We strongly suggest that you do not grant anyone else access to your login credentials. You will be held liable for all use or misuse of the Website under your login credentials. Flight Club VIP will never email you a request to disclose your login information via email or email links at which you will be prompted to submit the same. It is always best for you to type in the URL for any website, including the Website, directly into your browser.</p>
<p><strong>Bookings of VIP Packages on Flight Club VIP</strong></p>
<p>By submitting a booking inquiry through Flight Club VIP, the Client is initiating a process that will, if the Client and the Tour Provider complete the process, result in the Client’s entry into a direct (legally binding) contractual relationship with the respective Tour Provider according to its terms and conditions. Flight Club VIP always and only acts as an intermediary between the Client and the Tour Provider, as the booking and payment processing agent (as applicable) of the Tour Provider, but never as a principal to the transaction. You agree that Flight Club VIP’S role is limited to the foregoing.</p>
<p>If the Client wishes to accept the Booking Proposal, the Client must clearly accept the Booking Proposal via email. Following the Client’s clear acceptance, the Tour Operator will confirm availability of the services as described in the Booking Proposal and then the Client will receive, through the Flight Club VIP email communication, a payment link for the processing of the Client’s payment to the Tour Provider (the “Payment Request”). To complete the purchase of services described in a Booking Proposal, the Client must promptly (and in any event within the time period stated in the Payment Request) pay all amounts required under the Payment Request.</p>
<p>Upon confirmation and clearance of the first amount required to be paid by the Client in the Payment Request, which amount may be either a deposit or the entire price, as indicated in the Payment Request, the Tour Provider will issue, through Flight Club VIP email communications , a confirmation of payment and booking, and upon such confirmation, the Client and the Tour Provider shall be deemed to have entered into a legally binding contractual relationship for services according to the applicable Booking Proposal.</p>
<p><strong>Invoice, Payment, and Payment Cards</strong></p>
<p>If, as above, the Client timely accepts the terms of a Booking Proposal, the Tour Operator will provide a payment link to Flight Club VIP. Flight Club VIP will use reasonable efforts to process the applicable charges on the Client’s payment card, as payment processing agent for the Tour Provider. Flight Club VIP may, on behalf of the Tour Provider, send the client an invoice or other record of billing and payment processing.</p>
<p>The Client must ensure that all payment card or other payment information remains up to date. Failure to submit all installments may result in the cancellation or delay of a booking, among other remedies.</p>
<p>Flight Club VIP disclaims all responsibility or liability for any problems arising out of the processing of payment card charges and, if any payment card charge fails to process, the Client’s booking may be rejected and the Client may be required to repeat the process of enquiring for a Booking Proposal and submitting payment therefor. Late payment, wrong bank, debit or credit card details, invalid credit/debit cards or insufficient funds are at the Client’s risk and may result in cancellation or rejection by the Tour Provider. In such case, the Client may not be entitled to refund of any prepaid amounts if so provided in the policies of the applicable Tour Provider.</p>
<p>All payment card fraud, unauthorized payment card use, or similar circumstances should be reported to the payment card issuer in accordance with its reporting rules and procedures. In addition, if you notice any unusual or unauthorized activity with respect to any charges on your payment card relative to any bookings through the Website, you should immediately contact Flight Club VIP by email to info@flightclub.vip with ‘credit card fraud’ in the subject line, and provide us with all information and details of such activity.</p>
<p>The protections offered by Flight Club VIP pertain only to payment card bookings made on the Website using our secure server. We cannot offer any service whatsoever with respect to payments made directly to Tour Providers or other third parties.</p>
<p><strong>Insurance Coverage</strong></p>
<p>Each Client is responsible to acquire insurance or otherwise cover travel risks such as medical, accident, property, repatriation and cancellation.</p>
<p><strong>Tour Provider Terms</strong></p>
<p>The general cancellation and no-show policy of the applicable Tour Provider is made available on the Website during payment checkout, and may also be set forth in Booking Proposals provided to the Client. Each Client is responsible to be aware of the booking policies of the applicable Tour Provider, especially the pre-payment, cancellation and the no show policy of the Tour Provider, thoroughly prior to accepting a Booking Proposal or making payment to confirm the same.</p>
<p>By accepting a Booking Proposal and submitting payment under a Payment Request to the Tour Provider on the Website, the Client accepts and agrees to the relevant cancellation and no-show policy of the Tour Provider, and to any additional terms and conditions of the Tour Provider that may apply to the Client’s booking. If the Client wishes to review, adjust or cancel a booking, the Client must revert to the Booking Proposal or Payment Request from the Tour Provider and follow the instructions therein. The Client may be charged for cancellation in accordance with the Tour Provider’s cancellation, (pre)payment and no-show policy. Flight Club VIP is not involved in the policies and rules that apply as between a Client and the Tour Provider relative to booked VIP Packages or Single Services.</p>
<p><strong>Disclaimer and Limitation of Liability</strong></p>
<p>Flight Club VIP is neither directly nor indirectly organizing VIP Packages nor any other tourist services. You acknowledge and agree that all such services are provided by the Tour Providers and other relevant third parties, and while Flight Club VIP will use reasonable efforts to support Clients regarding problems with Tour Providers, Single Services, and VIP Packages as otherwise described herein, each Client agrees to look solely to the Tour Provider for any legal redress relative to the bookings enquired about or obtained through the Website or otherwise through Flight Club VIP.</p>
<p>Flight Club VIP hereby disclaims and excludes any liability arising out of the Website, any Client’s use of the Website, any bookings enquired about or obtained through the Website, or with respect to any VIP Package, to the fullest extent permissible by applicable law.</p>
<p>You agree that Flight Club VIPs’ sole role is as host of information provided by Tour Providers and payment and booking processing agent on behalf of the Tour Provider. You agree that Flight Club VIP is neither a principal to any booking or VIP Package transaction nor liable for any aspect of the VIP Package, the Tour Provider’s conduct, or any failure on the part of the Tour Provider.</p>
<p>The sale of VIP Packages and Single Services will be governed by the Tour Providers’ terms and conditions and any claims arising out of a VIP Package or a Tour Provider’s conduct must be claimed solely against the Tour Provider. Accordingly, to the extent permitted by law, neither Flight Club VIP, nor any of the company’s directors, managers, employees, representatives, subsidiaries, affiliated companies, distributors, affiliate (distribution) partners, licensees, agents or others involved in creating, sponsoring, promoting, or otherwise making available the site and its contents shall be liable for any direct and/or indirect damages to the Client and/or any other third parties, including without limitation for (i) any special or consequential losses or damages, any loss of production, loss of profit, loss of revenue, loss of contract, loss of or damage to goodwill or reputation, loss of claim, (ii) any inaccuracy relating to the (descriptive) information (including rates and ratings) of the Single Services or VIP Packages as made available on the website, (iii) the services rendered or the products offered by the Tour Provider or other business partners, (iv) any (direct, indirect, consequential or punitive) damages, losses or costs suffered, incurred or paid by the client, pursuant to, arising out of or in connection with, the use, inability to use or delay of the Website, or (v) any (personal) injury, death, property damage, or other (direct, indirect, special, consequential) damages, losses or costs suffered, incurred or paid by the client, whether due to acts, errors, breaches, negligence, willful misconduct, omissions, non-performance, misrepresentations, tort or strict liability by or (wholly or partly) attributable to the VIP Packages or Single Services or any of the Tour Provider’s other business partners (including any of their employees, directors, officers, agents, representatives or affiliated companies) whose products or service are (directly or indirectly) made available, offered or promoted on or through the Website, including any (partial) cancellation, overbooking, strike, force majeure or any other event beyond Flight Club VIPs’ control.</p>
<p>In no event shall Flight Club VIP be liable for any demand, injuries, losses, claims, damages or any direct, incidental, special, consequential damages or economic loss, including but not limited to loss of profits or savings arising out of or in any way connected with the use of any data or information services displayed on the Website.</p>
<p>In case any or all of the above limitations or disclaimers of liability are unenforceable for any reason, you agree that the maximum you may claim against Flight Club VIP shall be an amount equal to US$25.00.”</p>
	

<?php
			        	 //the_content();
			        }
			        } ?>	
        		</div>
        	</div>        	
        </div>
    </section>
</div>
<?php
get_footer();?>